# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      APP_ID: ${{ secrets.APP_ID }}
      MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

      SENTRY_DSN: ''

      URL: ${{ secrets.URL }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
