name: Report to packtracker.io

on: [push]

jobs:

  build:

    name: report

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run next.js build

        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

          SENTRY_DSN: ''

          URL: ${{ secrets.URL }}

          CYPRESS_PROJECT_KEY: ${{ secrets.CYPRESS_PROJECT_KEY }}

          PT_PROJECT_TOKEN: ${{ secrets.PACKTRACKER_PROJECT_ID }}

        run: npm ci && npm run build